# Generated by Django 4.1.2 on 2025-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0004_auto_20230810_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveitemtax',
            name='flat_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
