# Generated by Django 4.1.2 on 2025-10-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0005_alter_eveitemtax_flat_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveitemtax',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
