# Generated by Django 4.1.2 on 2025-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0006_eveitemtax_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveitemtax',
            name='needs_update',
            field=models.BooleanField(default=True),
        ),
    ]
